name: sync

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '*.adoc'
  schedule:
    - cron: '0 2 * * *'  # every day at 1:00
  pull_request:
    paths-ignore:
      - '*.adoc'
      - .github/workflows/annotate.yml
  workflow_dispatch:

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "https://${{ secrets.ISO_BITBUCKET_USERNAME_URLENCODED }}:${{ secrets.ISO_BITBUCKET_PAT_TOKEN_URLENCODED }}@sd.iso.org/bitbucket-pilot/scm/isotc184sc4/wg12-stepmod.git"
          destination_repo: "https://${{ secrets.METANORMA_CI_USERNAME }}:${{ secrets.METANORMA_CI_PAT_TOKEN }}@github.com/metanorma/iso-10303-stepmod-wg12"
          source_branch: "refs/remotes/source/*"
          destination_branch: "refs/heads/*"
